### ISSUE TITLE
Add BoolField

### ISSUE THREAD

**Issue by travisjungroth** [travisjungroth/formlessness#111]
See [IntField](https://github.com/travisjungroth/formlessness/blob/9d4f4270db381a0e3508ae46cfa2ca8bf951fd9f/formlessness/fields.py#L132) for the pattern. Use [checkbox](https://github.com/travisjungroth/formlessness/blob/9d4f4270db381a0e3508ae46cfa2ca8bf951fd9f/formlessness/widgets.py#L11) as the default widget.

**Comment by marsjoy** [comment]
https://github.com/travisjungroth/formlessness/pull/152
